# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-issues' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-issues
  pod 'Alamofire', '~> 5.2'
  pod 'Moya', '~> 14.0'
  pod 'Moya-ModelMapper', '~> 10.0'

  target 'github-issuesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'github-issuesUITests' do
    # Pods for testing
  end

end
