# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-issues' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-issues

  target 'github-issuesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github-issuesUITests' do
    # Pods for testing
  end

end
